### PR TITLE
Added Swift Package Manager

### PR DESCRIPTION
**Pull request by maxxfrazer**
- [x] Added `Package.swift`
- [x] Bumped Swift version to 5.0
- [x] Fix CI Errors

### CODE REVIEW

**Comment by maxxfrazer** [comment]
@krisk I believe this is ready to merge now; I noticed the existing PRs which put the swift version to 5.0 fail on CI & the activity looks pretty dead there.
Hopefully this can get merged and people can use your repo with the upcoming Xcode 11!

**Comment by hugovanderlei** [comment]
can you please accept this PR? I can't use it because is not working with Swift 5.
Thanks!

**Comment by maxxfrazer** [comment]
@krisk these changes are pretty small, but necessary for anyone using the latest public Xcode.
Any chance we could get this reviewed & merged?

**Comment by maxxfrazer** [comment]
@krisk fixed the merge conflicts, please review and merge when possible. 🙏🏼

**Pull request merged**
