### PR TITLE
Struct support

### PR DESCRIPTION
**Pull request by StevenSorial**
I don't know if there is a performance penalty to structs support or not, so I used it as a last resort if the original implementation failed.

### CODE REVIEW

**Comment by krisk** [comment]
Nice. Could you also add some tests to [Tests.swift](https://github.com/krisk/fuse-swift/blob/master/Example/Tests/Tests.swift)?

**Comment by StevenSorial** [comment]
Sure.
if you don't mind me asking, what was achieved by using 

```
let object = item as AnyObject
..
let selector = Selector(property.name)
let value = object.perform(selector).takeUnretainedValue() as? String
```
vs simply
```
let value = item.name
```

**Comment by StevenSorial** [comment]
I have ditched reflection for a simple property accessing to support more use cases. it shouldn't be a performance issue given Swift Copy-On-Write. This is a breaking change for `Fuseable` users, but it should be a simple one.
Tests and Docs are updated accordingly.

**Comment by StevenSorial** [comment]
@krisk

**Comment by mthole-old** [comment]
Good stuff here, thanks @StevenMagdy !

**Comment by StevenSorial** [comment]
The branch is updated to reflect the latest changes. I hope it will be merged one day 🙏

**Pull request merged**
